### ISSUE TITLE
Moodle 3.5, view stats page for a course gives error

### ISSUE THREAD

**Issue by mgancarzdsi** [catalyst/moodle-report_coursesize#11]
Hi Dan, On Moodle 3.5.1, clicking the 'view stats' button (url: /report/coursesize/course.php?id=###)  next to a course gives the following error 6 times:

Notice: Undefined property: stdClass::$sum in /var/www/html/learning-staging.desouzainstitute.com/report/coursesize/course.php on line 56

It shows 0 MB in size for each of the plugin types listed. 
Example:
Course size - Name of course
Summary of plugin types - NOTE this may be lower than the main course listing and is probably more accurate.
Approx 886MB is shared with other courses.
Plugin	Size
course	0MB
mod_forum	0MB
mod_page	0MB
mod_resource	0MB
mod_scorm	0MB
question	0MB

**Comment by danmarsden** [comment]
thanks! - looks like some dodgy sql that isn't cross-db compatible - I've just pushed through a fix that should sort it!
