### ISSUE TITLE
Debugging message shown while using this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [catalyst/moodle-report_coursesize#13]
With debugging set to DEVELOPER, Moodle reports:

Class coursecat is now alias to autoloaded class core_course_category, course_in_list is an alias to core_course_list_element. Class coursecat_sortable_records is deprecated without replacement. Do not include coursecatlib.php

    line 31 of /lib/coursecatlib.php: call to debugging()
    line 27 of /report/coursesize/index.php: call to require_once()

I want to use the information from this plugin to better understand the mess i made in my University Moodle site, as I described in https://moodle.org/mod/forum/discuss.php?d=381648#p1538964.

**Comment by danmarsden** [comment]
cool - thanks for the report - I hadn't noticed that one yet - looks like an easy fix.
