### ISSUE TITLE
Add assignment size in report

### ISSUE THREAD

**Issue by prbond** [catalyst/moodle-report_coursesize#14]
Could you add assignment size in report.
Reports take up space.

Regards

**Comment by danmarsden** [comment]
each course line has a link to "Stats" that provides some more detailed information on the location of the files with the specific course. Adding extra columns to the main report is not something we are currently looking at - this report is already quite heavy on the DB, adding further columns would potentially make the report too slow to load on larger sites. 

Pull requests and or funding for improvements are always welcome though!

**Comment by prbond** [comment]
Could you help me or say how develop this feature ? for maybe a pull request if i success.

**Comment by danmarsden** [comment]
Sure - drop me a line privately and I can provide information on our consulting rates.
