### ISSUE TITLE
Listed Compatibility on Moodle.org

### ISSUE THREAD

**Issue by michael-milette** [catalyst/moodle-report_coursesize#24]
The plugin is currently listed as only being compatible with Moodle up to version 3.7. I have tested it in 3.8 and read that others have tested it in 3.9. I didn't see any reports on Moodle 3.10 compatibility yet. Could you please update the compatibility list so that the plugin can be installed from within Moodle or from Moodle.org?

**Comment by danmarsden** [comment]
Hey Michael,

Yes - we don't publish our plugins to the moodle.org plugins db regularly - as with all our plugins the latest version is always in github.

I might take a look at re-publishing a bunch of our plugins sometime next year - thanks!
