### ISSUE TITLE
Request: Please add git release tags

### ISSUE THREAD

**Issue by danowar2k** [catalyst/moodle-report_coursesize#28]
It would be very helpful for automatic deployment if you could add the git tags for each release you're doing.

Here are the commands to add the tags for the two recent release on moodle.org:

```
# Add tag for 2.2 (https://moodle.org/plugins/report_coursesize/2.2/16825)
git tag -a "2.2" 1849dc9441086cd3b47b74cc1a13464ca97f0dfc -m "ADDITIONAL_OPTIONAL_INFO"
# Add tag for 3.6 (https://moodle.org/plugins/report_coursesize/3.6/19641)
git tag -a "3.6" c9f2b9dea10c42e9bdb2433f3b9b5bc17b3b1551 -m "ADDITIONAL_OPTIONAL_INFO"
```

**Comment by danmarsden** [comment]
HI @danowar2k, you might be aware that we maintain a large number of plugins that we share with the community. We do not use tags in our release process internally and don't currently have plans to use them when updating our plugins. We are planning to start automatically pushing updates to the moodle.org plugins db but we are not planning to use tags to do this.
You might want to look at alternatives for managing your automated release process.

Thanks!
