### ISSUE TITLE
Async report generation

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-report_coursesize#29]
On a big instances generating report can take a long time. Would be nice to move it to async task. 

The work has already started see https://github.com/catalyst/moodle-report_coursesize/compare/master...asyncprocess

However, that diff is adding a lot of things and it would have been better to break it up into smaller features prs and get them each merged instead of forking with a mega patch.

**Comment by danmarsden** [comment]
basic async support is now available in the moodle 3.9 branch and higher - we still need to backport this to the totara branch but that's covered in #32 - closing this one off.

Note - the old netspot async branch contains different table structures that have not been replicated here - any sites using that old branch will need to manually drop the tables before upgrading to the new version.

Longer term plan is to replace the report tables using moodle's reportbuilder (#33) and potentially the Totara branch could use Totara's reportbuilder for rendering the report which will bring the other sorting/filtering options similar to the old asyncprocess branch.

closing.
