### ISSUE TITLE
HARDCODED?

### ISSUE THREAD

**Issue by dinism** [catalyst/moodle-report_coursesize#35]
**Testing in Moodle 4.0 BETA**
I'm a PT-PT translator.
![imagem](https://user-images.githubusercontent.com/14828021/158018736-4e93ccdb-ad2b-4fc8-86b8-9057ae60f2ce.png)

**Comment by danmarsden** [comment]
thanks for the report - I've just pushed a fix into the repo which should auto-update in the moodle.org plugins repo when all tests pass.
