### ISSUE TITLE
Course size report not accesible for Manager Role Users anymore

### ISSUE THREAD

**Issue by leandrohpedro** [catalyst/moodle-report_coursesize#36]
Hello, I have installed the latest version of the module and found that the "course size report" option does not show up in the "Reports" section for Manager Role Users. I´ve checked the permissions under "define role" for a  "Manager" and the permission is "Allow". Could you please help me out to know if there is something else I have to enable?

**Comment by danmarsden** [comment]
thanks for the report - there was a bug with the way I'd built the settings.php file - I've pushed a fix into the repository here and it should auto-publish a new version to the plugins db in the next hour or so once tests all pass.

**Comment by leandrohpedro** [comment]
Thanks for your prompt response. I updated it in my test environment and now it shows me the report with the Manager Role fine.
