### ISSUE TITLE
Error reading from database? 

### ISSUE THREAD

**Issue by ibolpd** [catalyst/moodle-report_coursesize#44]
Hi all, 
We are running the report_coursesize plugin on the site, and it gives back "Error reading from database". I have checked with the hosting provider and they have stated that "this does not appear to be a server issue as the database server is still accessible for all other users and this only seems to be affecting this plugin". 

We have tried running it on different machines and from different browsers. 

What tips do you have on resolving the issue? 

My best,
Neti

**Comment by danmarsden** [comment]
does your host use MS Sql as the database? - (I hope not...) :-( 

but if so... #39 might be the issue you are having there - you can turn off the async setting to see if that helps as described in that issue.

**Comment by ibolpd** [comment]
Thank you for the tip! The database is MySQL
Moodle: 3.7.2 (Build: 20190909)  
Report_coursesize: 3.6(2019052800) 

It still gives the "Error reading from database", trying at various times of day. 
Do you perhaps have any tips on what can be done further?

**Comment by danmarsden** [comment]
Hi there, 

Moodle 3.7 has been out of support for almost 2 years so we don't support it here either.
Probably best to focus any time you have on upgrading to a more recent supported release of Moodle.

thanks!
