### ISSUE TITLE
Misleading top 10 users section.

### ISSUE THREAD

**Issue by OT-AndreyUskov** [catalyst/moodle-report_coursesize#45]
The report should not include in top 10 users section files taken into account in courses section.
This section should show personal files that belong to the user but not to the courses.
In its current state this section shows disk space taken by all files uploaded by users to all courses. It is interesting but it does not help much when you try to figure out what occupies the disk space.

**Comment by danmarsden** [comment]
@OT-AndreyUskov sounds like a feature-request that you really want there... The "TOP 10" users section is used by our clients to identify which users are responsible for the largest amount of files uploaded to the LMS - quite often these are staff that may need some education around compression/cleaning up of their own content etc.

I'm closing this as it's not misleading, it's just that you want a different report than is implemented currently - feel free to submit a pull request adding a new report to the plugin that achieves what you need or reach out if you would like to fund further improvements. - thanks! :-)
