### ISSUE TITLE
Export to CSV error

### ISSUE THREAD

**Issue by neeesn** [catalyst/moodle-report_coursesize#46]
Thanks for a good plugin.

We have discovered a bug. When clicking the Export CSV button, the data is outputtet on the screen, and is not downloaded as a file. 
We have a lot of courses and its a problem for the teachers.

Kind regards.
Henrik Sune Pedersen

**Comment by danmarsden** [comment]
Thanks for the report. I've just pushed a fix for that into the github repo here.

**Comment by BennyJuel** [comment]
I have found another bug. There is no text-qualificator around the coursename like the categori. So if there is a comma in the coursename it is spread over more columns in Excel.

It would be nice if the size not were mwntined in GB and MB. Then it would be possible to count on the size from different categories. 10.1GB should be mentioned as 10.100.000 instead.

**Comment by danmarsden** [comment]
thanks - please report that as a separate issue, feel free to help by submitting a pull request with the fix too.
