### ISSUE TITLE
Update SQL does not work on SQL Server

### ISSUE THREAD

**Issue by matthias-gass** [catalyst/moodle-report_coursesize#49]
Ladies and Gents,

the report coursesize plugin relies on the moodle cron job to do the calculation of course file sizes. During execution of the moodle cron job an update statement is executed that is derived from the following sql template found in the file moodle\report\coursesize\classes\task\report_async.php:
```
$sql = "UPDATE {report_coursesize} rc
SET backupsize = (SELECT bf.filesize FROM ($basesql) bf WHERE bf.course = rc.course)";
```

SQL Server cannot execute this statement because an alias on the update table (here: "rc") is not allowed in this dialect and hence course size cannot persisted in the database. As a quick fix I implemented the following solution which works on SQL Server. However I did not test whether this works with the other db providers.

```
$sql = "UPDATE {report_coursesize} 
SET backupsize = (SELECT bf.filesize FROM ($basesql) bf WHERE bf.course = {report_coursesize}.course)";
```

I'm using [Release 4.2](https://moodle.org/plugins/report_coursesize/4.2/27516)

Best regards
Matthias

**Comment by danmarsden** [comment]
Duplicates #39
