### ISSUE TITLE
SQL query hangs

### ISSUE THREAD

**Issue by jderriks** [catalyst/moodle-report_coursesize#5]
`SELECT cx.id, cx.contextlevel, cx.instanceid, cx.path, cx.depth, size.filessize, backupsize.filessize as backupsize, sharedsize.sharedsize as sharedsize FROM mdl_context cx  INNER JOIN ( SELECT f.contextid, sum(f.filesize) as filessize FROM mdl_files f GROUP BY f.contextid ) size on cx.id=size.contextid LEFT JOIN ( SELECT f.contextid, sum(f.filesize) as filessize FROM mdl_files f WHERE component like 'backup' GROUP BY f.contextid ) backupsize on cx.id=backupsize.contextid LEFT JOIN ( SELECT f.contextid, SUM(f.filesize) as sharedsize FROM mdl_files f INNER JOIN mdl_context cx ON f.contextid = cx.id WHERE contenthash in (SELECT contenthash FROM mdl_files WHERE filesize > 0 AND filearea <> 'draft' GROUP BY contenthash  HAVING count(*) > 1)  AND f.filesize > 0  AND f.filearea <> 'draft'  GROUP BY f.contextid) sharedsize on cx.id=sharedsize.contextid  ORDER by cx.depth ASC, cx.path ASC`

Is taking too long on al large site to give any results. Moodle 3.0.9

**Comment by danmarsden** [comment]
we've found that it works ok on larger Postgres sites (better than the previous sharedsize query) - what database engine and version are you running on your site?

**Comment by jderriks** [comment]
mysql  Ver 14.14 Distrib 5.5.52, for Linux (x86_64) using readline 5.1

Tables: InnoDB v10 compact.
Running on redhat linux.

Not even a big system: 116621 rows in the files table. Total sizes about 280GB.

**Comment by jderriks** [comment]
Workarounds:
It's the third join to calculate the sharedsize that causes the query to run too log on our slow redhat servers.
This only happens if you install the plugin on Moodle 3.0 and higher. The old version is less complicated and much faster so I recommend version 1 (2011081300) over the 2016 version 2. Remove the plugin, download the older version and install that.

Or you can also remove the sharedsize part from the  $sizesql query so that it looks like this and it will report 0 as the sharedsize column:
`$sizesql = 'SELECT cx.id, cx.contextlevel, cx.instanceid, cx.path, cx.depth,
            size.filessize, backupsize.filessize as backupsize, NULL as sharedsize' .
           ' FROM {context} cx ' .
           ' INNER JOIN ( ' . $subsql . $groupby . ' ) size on cx.id=size.contextid' .
           ' LEFT JOIN ( ' . $subsql . $wherebackup . $groupby . ' ) backupsize on cx.id=backupsize.contextid' .
           ' ORDER by cx.depth ASC, cx.path ASC';
`

**Comment by jgilevich** [comment]
> $sizesql = 'SELECT cx.id, cx.contextlevel, cx.instanceid, cx.path, cx.depth, size.filessize, backupsize.filessize as backupsize, NULL as sharedsize' . ' FROM {context} cx ' . ' INNER JOIN ( ' . $subsql . $groupby . ' ) size on cx.id=size.contextid' . ' LEFT JOIN ( ' . $subsql . $wherebackup . $groupby . ' ) backupsize on cx.id=backupsize.contextid' . ' ORDER by cx.depth ASC, cx.path ASC';
> 
Worked for me, thank you!

**Comment by mkpelletier** [comment]
This workaround is effective on 3.3.  We have a dedicated db server (octocore with 32gb) and the original query and the improvements from commit ee1573a still crash our site.

**Comment by danmarsden** [comment]
Thanks @mkpelletier - I'm thinking of dumping the shared size calculation from the main view as I've added a new course level report that shows a more accurate shared size value and a breakdown of the components that use the files. There doesn't seem to be an effficient cross-db compatible query I can write to get this data for all courses.

Alternatively we could write some db specific queries - showing the shared size info for postgres sites and hiding it for mysql based sites. but I think it probably makes more sense to remove it. I'll try to get to this at some point.

**Comment by mkpelletier** [comment]
Thanks Dan.  I could see this working if rather than the multiple inner joins, we include a link to the report on each course (i.e. drill-down).
