### ISSUE TITLE
Should multiple instances of the same file within a course, identified by the same contenthash, contribute to the total course size multiple times?

### ISSUE THREAD

**Issue by Arvaloez** [catalyst/moodle-report_coursesize#61]
Hello,

I was reviewing the course size report and noticed that the same file appears multiple times within a course. Each instance of the file seems to be contributing to the total course size. However, my understanding is that the file is unique, and its contenthash represents its location. Each instance references the same file without duplicating the storage space.

Could you please confirm if my interpretation is correct, or if I might be misunderstanding how the report calculates the total size?

Thank you for your assistance!

Best regards,
Alexander

**Comment by danmarsden** [comment]
@Arvaloez at the top of the report the following text is displayed:
"This report only provides approximate values, if a file is used multiple times within a course or in multiple courses the report counts each instance even though Moodle only stores one physical version on disk."

The individual course reports (accessed by clicking on the coursename) are more accurate. 

On sites with large amounts of data, calculating unique data is extremely performance heavy and in most cases, an approximate value is enough to help identify the large courses in your site. There is an existing "feature request" open related to this #2 so I'm closing this one off.
