### ISSUE TITLE
cannot run reom the command line

### ISSUE THREAD

**Issue by doylejl** [catalyst/moodle-report_coursesize#9]
Hi,

I'm trying to run this course size script but it keeps timing out when i run it, would it be possible to run this script from the command line?

thanks

**Comment by danmarsden** [comment]
typically it's the total disk size that causes the timeout - we run an internal automated task that stores the totaldisk used for each of our clients and inserts it into the db.

also - make sure you have "pathtodu" configured in your Moodle admin settings.

if pathtodu is set or you are not able to set it, you could try uncommenting this line:
https://github.com/catalyst/moodle-report_coursesize/blob/master/index.php#L56

we don't currently have a cli version of this, but pull requests are always welcome.

**Comment by doylejl** [comment]
Hi Dan,

 

Thanks for your reply, I do have the “path to du” set however I think the issue with the timeout is to do with sheer volume as we have 11k courses and 1.7 million files uploaded into our moodle 

 

Regards

 

John

**Comment by danmarsden** [comment]
make sure you're using the latest code from github and try uncommenting the line I mentioned to see if it makes any difference. We do have this running on some large sites and it works ok for us. Feel free to get in touch privately with us if you would like to fund some further development - pull request are always welcome too. Thanks.
